//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBPWA_API.Business.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassPackage
    {
        public long Id { get; set; }
        public int ClassId { get; set; }
        public int ModelId { get; set; }
        public int PackageId { get; set; }
        public Nullable<long> NoMetallic { get; set; }
        public Nullable<long> Metallic { get; set; }
        public Nullable<long> Designo { get; set; }
        public Nullable<long> DesignoMagno { get; set; }
    
        public virtual Package Package { get; set; }
    }
}
